[colors.bright]
black = "#444444"
blue = "#0072df"
cyan = "#47dfd0"
green = "#abe15b"
magenta = "#9a5feb"
red = "#ff2740"
white = "#ffffff"
yellow = "#ffd242"

[colors.normal]
black = "#232323"
blue = "#006df8"
cyan = "#00c8db"
green = "#8ce10b"
magenta = "#6d43a6"
red = "#ff000f"
white = "#ffffff"
yellow = "#ffb900"

[colors.primary]
foreground = "#282c34"
background = "#ffffff"

[cursor]
thickness = 0.05

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
# size = 20.0
size = 16.0

[font.bold]
# family = "CaskaydiaCove Nerd Font Propo"
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font Propo"
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "CaskaydiaCove Nerd Font Propo"
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font Propo"
family = "SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.97

[window.padding]
x = 15
y = 15
